# Copyright (c) 2019 Ansible Project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


class ModuleGroup(object):
    MODULES = [
        'azure_rm_acs',
        'azure_rm_aks',
        'azure_rm_aks_facts',
        'azure_rm_appserviceplan',
        'azure_rm_appserviceplan_facts',
        'azure_rm_availabilityset',
        'azure_rm_availabilityset_facts',
        'azure_rm_containerinstance',
        'azure_rm_containerregistry',
        'azure_rm_deployment',
        'azure_rm_dnsrecordset',
        'azure_rm_dnsrecordset_facts',
        'azure_rm_dnszone',
        'azure_rm_dnszone_facts',
        'azure_rm_functionapp',
        'azure_rm_functionapp_facts',
        'azure_rm_image',
        'azure_rm_keyvault',
        'azure_rm_keyvaultkey',
        'azure_rm_keyvaultsecret',
        'azure_rm_loadbalancer',
        'azure_rm_loadbalancer_facts',
        'azure_rm_managed_disk',
        'azure_rm_managed_disk_facts',
        'azure_rm_manageddisk',
        'azure_rm_manageddisk_facts',
        'azure_rm_mysqldatabase',
        'azure_rm_mysqldatabase_facts',
        'azure_rm_mysqlserver',
        'azure_rm_mysqlserver_facts',
        'azure_rm_networkinterface',
        'azure_rm_networkinterface_facts',
        'azure_rm_postgresqldatabase',
        'azure_rm_postgresqldatabase_facts',
        'azure_rm_postgresqlserver',
        'azure_rm_publicipaddress',
        'azure_rm_publicipaddress_facts',
        'azure_rm_resource',
        'azure_rm_resource_facts',
        'azure_rm_resourcegroup',
        'azure_rm_resourcegroup_facts',
        'azure_rm_resourcegroup_info',
        'azure_rm_securitygroup',
        'azure_rm_securitygroup_facts',
        'azure_rm_sqldatabase',
        'azure_rm_sqlserver',
        'azure_rm_sqlserver_facts',
        'azure_rm_storageaccount',
        'azure_rm_storageaccount_facts',
        'azure_rm_storageblob',
        'azure_rm_subnet',
        'azure_rm_virtualmachine',
        'azure_rm_virtualmachine_extension',
        'azure_rm_virtualmachine_facts',
        'azure_rm_virtualmachine_scaleset',
        'azure_rm_virtualmachine_scaleset_facts',
        'azure_rm_virtualmachineimage_facts',
        'azure_rm_virtualnetwork',
        'azure_rm_virtualnetwork_facts',
        'azure_rm_webapp',
    ]
